steps:
  # Build the Docker image for email service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stock-scribe-email:latest', '-f', 'Dockerfile.email', '.']
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stock-scribe-email:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stock-scribe-email'
      - '--image'
      - 'gcr.io/$PROJECT_ID/stock-scribe-email:latest'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/stock-scribe-email:latest'

# Build options
options:
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY
